name: Job Dependencies with Conditional Execution

on:
  workflow_dispatch:

jobs:
  job_a:
    runs-on: ubuntu-latest
    outputs:
      run_b: ${{ steps.configure.outputs.run_b }}
    steps:  
      - name: Configure
        id: configure
        run: |
          # Check if branch is main
          run_b=${{ github.ref == 'refs/heads/main' }}
          echo "run_b=$run_b" >> $GITHUB_OUTPUT
  job_b:
    runs-on: ubuntu-latest
    needs: job_a # This job depends on job1
    # Only run if job_a says so
    if: needs.job_a.outputs.run_b == 'true' # Note that the output is a string, so we compare it to 'true' instead of true
    steps:
      - run: echo "This is job B, which runs only if job A's condition is met."
  
  job_c:
    runs-on: ubuntu-latest
    needs: job_b
    if: ${{ !failure() && !cancelled() }} # Only run if job B didn't fail or was cancelled
    steps:
      - run: echo "This is job C, which runs only if job B was either successful or skipped."