name: Workflow Dispatch with Inputs
run-name: "${{ github.event_name == 'workflow_dispatch' && format('{0} from \"{1}\"', github.workflow, github.ref_name) || '' }}"

on:
  push:
    branches: [main]

  workflow_dispatch:
    inputs:
      # Arguments
      artifact_name:
        type: string # Text field
        description: 'Artifact identifier:'
        required: true
      data_source:
        type: choice # Dropdown selection
        description: 'Data source:'
        default: 'sample'
        options:
          - sample
          - test
          - production
      send_notification:
        type: boolean # Checkbox
        description: 'Send email notification'
        default: true

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      data_source: ${{ steps.resolve-inputs.outputs.data_source }}
      send_notification: ${{ steps.resolve-inputs.outputs.send_notification }}
      artifact_name: ${{ steps.resolve-inputs.outputs.artifact_name }}
    steps:
      - name: Resolve Inputs
        id: resolve-inputs
        run: |
          # Set the defaults if triggered by push event to main branch
          data_source="${{ inputs.data_source || 'production' }}"
          send_notification="${{ inputs.send_notification || true }}"
          artifact_name="${{ inputs.artifact_name || 'prod-artifact' }}"

          # Expose as outputs
          echo "data_source=$data_source" >> $GITHUB_OUTPUT
          echo "send_notification=$send_notification" >> $GITHUB_OUTPUT
          echo "artifact_name=$artifact_name" >> $GITHUB_OUTPUT
          
  
  # Example job that uses the configured inputs
  job1:
    needs: configure
    runs-on: ubuntu-latest
    steps:
      - name: Use Configured Inputs
        run: |
          echo "Data Source: ${{ needs.configure.outputs.data_source }}"
          echo "Send Notification: ${{ needs.configure.outputs.send_notification }}"
          echo "Artifact Name: ${{ needs.configure.outputs.artifact_name }}"
