name: Reusable Workflow Example

on:
  # `workflow_call` makes the workflow callable from other workflows
  workflow_call:
    inputs:
      run_tests:
        type: boolean
        description: 'Run tests before building'
        required: true
    # Need to explicitly define the outputs here
    outputs:
      example_output:
        description: 'An example output from the reusable workflow'
        value: ${{ jobs.job1-example.outputs.example_output }} # Reference the output from the job
  
  # In most cases, it's also useful to manually trigger these type of workflows
  # Unfortunately, we need to duplicate the input definitions here for the dispatch trigger
  workflow_dispatch:
    inputs:
      run_tests:
        type: boolean
        description: 'Run tests before building'
        required: true

jobs:
  job1-example:
    runs-on: ubuntu-latest
    # Output of the job is defined here, so it can be referenced as an output of the workflow
    outputs:
      # The job output itself is defined in one of the steps (so many references, I know)
      example_output: ${{ steps.example_step.outputs.hello_message }}
    steps:
      - name: Example Step
        id: example_step
        run: |
          echo "This is an example step"
          echo "hello_message=Hello from reusable workflow!" >> $GITHUB_OUTPUT